### ISSUE TITLE
v11 Checklist Issues

### ISSUE THREAD

**Issue by ericorosel** [sparkfun/FemtoBuck#4]
If the board's size or form is causing or the reason for any of the issues mentioned below, and said issue cannot be resolved without disrupting the size or form; just mention that. I understand that the size/form of this board is an important selling point.

(1) U1 needs a value. I think "AL8805" would do.

(2) The left side of the current-set jumper is really close to the resistor pad below. If we could move this up even a little I think we would be saving ourselves some trouble on the manufacturing side.

(3) Looks like the bottom-side GND trace has some funny angles (other than 45 degrees)

(4) "OUT-" trace is entering the inductor pad at an angle

(5) Got an airwire on "CTRL_CH1"

(6) Need measures

(7) R1, R2, C1, C2 and L1 all need silk (TPlace) for footprints

(8) It would be nice to have a label for the current-set jumper. Maybe a note on the bottom of the board after the "6-36V 333/667mA" eg: "6-36V 333/667mA (OPEN/CLOSED)" Just a thought.

That's it.

**Comment by mhord** [comment]
1. Fixed.
2. Scooted up 0.005". That's getting dangerously close to the silk above it.
3. Oops. Fixed.
4. Fixed.
5. Fixed.
6. Fixed.
7. R1 and R2 had silk (?), fixed others in library.
8. It would be nice, but I think it would leave the board hopelessly crowded.
